// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceApp.proto

package cn.zsy.eg.google.protobuf.bean;

public final class UTraceLogBean {
  private UTraceLogBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TraceAppOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.zsy.eg.google.protobuf.bean.TraceApp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string sys = 2;</code>
     */
    boolean hasSys();
    /**
     * <code>required string sys = 2;</code>
     */
    String getSys();
    /**
     * <code>required string sys = 2;</code>
     */
    com.google.protobuf.ByteString
        getSysBytes();

    /**
     * <code>required string ts = 3;</code>
     */
    boolean hasTs();
    /**
     * <code>required string ts = 3;</code>
     */
    String getTs();
    /**
     * <code>required string ts = 3;</code>
     */
    com.google.protobuf.ByteString
        getTsBytes();

    /**
     * <code>optional string mtype = 4;</code>
     */
    boolean hasMtype();
    /**
     * <code>optional string mtype = 4;</code>
     */
    String getMtype();
    /**
     * <code>optional string mtype = 4;</code>
     */
    com.google.protobuf.ByteString
        getMtypeBytes();

    /**
     * <code>optional string cfg = 5;</code>
     */
    boolean hasCfg();
    /**
     * <code>optional string cfg = 5;</code>
     */
    String getCfg();
    /**
     * <code>optional string cfg = 5;</code>
     */
    com.google.protobuf.ByteString
        getCfgBytes();

    /**
     * <code>required string code = 6;</code>
     */
    boolean hasCode();
    /**
     * <code>required string code = 6;</code>
     */
    String getCode();
    /**
     * <code>required string code = 6;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string span = 7;</code>
     */
    boolean hasSpan();
    /**
     * <code>optional string span = 7;</code>
     */
    String getSpan();
    /**
     * <code>optional string span = 7;</code>
     */
    com.google.protobuf.ByteString
        getSpanBytes();
  }
  /**
   * Protobuf type {@code cn.zsy.eg.google.protobuf.bean.TraceApp}
   */
  public  static final class TraceApp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.zsy.eg.google.protobuf.bean.TraceApp)
      TraceAppOrBuilder {
    // Use TraceApp.newBuilder() to construct.
    private TraceApp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TraceApp() {
      id_ = "";
      sys_ = "";
      ts_ = "";
      mtype_ = "";
      cfg_ = "";
      code_ = "";
      span_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TraceApp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sys_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              ts_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              mtype_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              cfg_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              code_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              span_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UTraceLogBean.internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UTraceLogBean.internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UTraceLogBean.TraceApp.class, UTraceLogBean.TraceApp.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYS_FIELD_NUMBER = 2;
    private volatile Object sys_;
    /**
     * <code>required string sys = 2;</code>
     */
    public boolean hasSys() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sys = 2;</code>
     */
    public String getSys() {
      Object ref = sys_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sys_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sys = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSysBytes() {
      Object ref = sys_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sys_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 3;
    private volatile Object ts_;
    /**
     * <code>required string ts = 3;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ts = 3;</code>
     */
    public String getTs() {
      Object ref = ts_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ts_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ts = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTsBytes() {
      Object ref = ts_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MTYPE_FIELD_NUMBER = 4;
    private volatile Object mtype_;
    /**
     * <code>optional string mtype = 4;</code>
     */
    public boolean hasMtype() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string mtype = 4;</code>
     */
    public String getMtype() {
      Object ref = mtype_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mtype_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mtype = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMtypeBytes() {
      Object ref = mtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CFG_FIELD_NUMBER = 5;
    private volatile Object cfg_;
    /**
     * <code>optional string cfg = 5;</code>
     */
    public boolean hasCfg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string cfg = 5;</code>
     */
    public String getCfg() {
      Object ref = cfg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cfg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cfg = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCfgBytes() {
      Object ref = cfg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cfg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 6;
    private volatile Object code_;
    /**
     * <code>required string code = 6;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string code = 6;</code>
     */
    public String getCode() {
      Object ref = code_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string code = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPAN_FIELD_NUMBER = 7;
    private volatile Object span_;
    /**
     * <code>optional string span = 7;</code>
     */
    public boolean hasSpan() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string span = 7;</code>
     */
    public String getSpan() {
      Object ref = span_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          span_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string span = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSpanBytes() {
      Object ref = span_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        span_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSys()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sys_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ts_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mtype_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cfg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, code_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, span_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sys_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ts_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mtype_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cfg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, code_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, span_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UTraceLogBean.TraceApp)) {
        return super.equals(obj);
      }
      UTraceLogBean.TraceApp other = (UTraceLogBean.TraceApp) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasSys() == other.hasSys());
      if (hasSys()) {
        result = result && getSys()
            .equals(other.getSys());
      }
      result = result && (hasTs() == other.hasTs());
      if (hasTs()) {
        result = result && getTs()
            .equals(other.getTs());
      }
      result = result && (hasMtype() == other.hasMtype());
      if (hasMtype()) {
        result = result && getMtype()
            .equals(other.getMtype());
      }
      result = result && (hasCfg() == other.hasCfg());
      if (hasCfg()) {
        result = result && getCfg()
            .equals(other.getCfg());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && getCode()
            .equals(other.getCode());
      }
      result = result && (hasSpan() == other.hasSpan());
      if (hasSpan()) {
        result = result && getSpan()
            .equals(other.getSpan());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasSys()) {
        hash = (37 * hash) + SYS_FIELD_NUMBER;
        hash = (53 * hash) + getSys().hashCode();
      }
      if (hasTs()) {
        hash = (37 * hash) + TS_FIELD_NUMBER;
        hash = (53 * hash) + getTs().hashCode();
      }
      if (hasMtype()) {
        hash = (37 * hash) + MTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMtype().hashCode();
      }
      if (hasCfg()) {
        hash = (37 * hash) + CFG_FIELD_NUMBER;
        hash = (53 * hash) + getCfg().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      if (hasSpan()) {
        hash = (37 * hash) + SPAN_FIELD_NUMBER;
        hash = (53 * hash) + getSpan().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UTraceLogBean.TraceApp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UTraceLogBean.TraceApp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UTraceLogBean.TraceApp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UTraceLogBean.TraceApp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UTraceLogBean.TraceApp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UTraceLogBean.TraceApp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UTraceLogBean.TraceApp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UTraceLogBean.TraceApp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UTraceLogBean.TraceApp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UTraceLogBean.TraceApp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UTraceLogBean.TraceApp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UTraceLogBean.TraceApp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UTraceLogBean.TraceApp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.zsy.eg.google.protobuf.bean.TraceApp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.zsy.eg.google.protobuf.bean.TraceApp)
        UTraceLogBean.TraceAppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UTraceLogBean.internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UTraceLogBean.internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UTraceLogBean.TraceApp.class, UTraceLogBean.TraceApp.Builder.class);
      }

      // Construct using cn.zsy.eg.google.protobuf.bean.UTraceLogBean.TraceApp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sys_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mtype_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        cfg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        span_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UTraceLogBean.internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_descriptor;
      }

      public UTraceLogBean.TraceApp getDefaultInstanceForType() {
        return UTraceLogBean.TraceApp.getDefaultInstance();
      }

      public UTraceLogBean.TraceApp build() {
        UTraceLogBean.TraceApp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UTraceLogBean.TraceApp buildPartial() {
        UTraceLogBean.TraceApp result = new UTraceLogBean.TraceApp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sys_ = sys_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mtype_ = mtype_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cfg_ = cfg_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.span_ = span_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UTraceLogBean.TraceApp) {
          return mergeFrom((UTraceLogBean.TraceApp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UTraceLogBean.TraceApp other) {
        if (other == UTraceLogBean.TraceApp.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasSys()) {
          bitField0_ |= 0x00000002;
          sys_ = other.sys_;
          onChanged();
        }
        if (other.hasTs()) {
          bitField0_ |= 0x00000004;
          ts_ = other.ts_;
          onChanged();
        }
        if (other.hasMtype()) {
          bitField0_ |= 0x00000008;
          mtype_ = other.mtype_;
          onChanged();
        }
        if (other.hasCfg()) {
          bitField0_ |= 0x00000010;
          cfg_ = other.cfg_;
          onChanged();
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000020;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasSpan()) {
          bitField0_ |= 0x00000040;
          span_ = other.span_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasSys()) {
          return false;
        }
        if (!hasTs()) {
          return false;
        }
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UTraceLogBean.TraceApp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UTraceLogBean.TraceApp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private Object sys_ = "";
      /**
       * <code>required string sys = 2;</code>
       */
      public boolean hasSys() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sys = 2;</code>
       */
      public String getSys() {
        Object ref = sys_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sys_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sys = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSysBytes() {
        Object ref = sys_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sys_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sys = 2;</code>
       */
      public Builder setSys(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sys_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sys = 2;</code>
       */
      public Builder clearSys() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sys_ = getDefaultInstance().getSys();
        onChanged();
        return this;
      }
      /**
       * <code>required string sys = 2;</code>
       */
      public Builder setSysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sys_ = value;
        onChanged();
        return this;
      }

      private Object ts_ = "";
      /**
       * <code>required string ts = 3;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string ts = 3;</code>
       */
      public String getTs() {
        Object ref = ts_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ts_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ts = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTsBytes() {
        Object ref = ts_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ts_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ts = 3;</code>
       */
      public Builder setTs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ts = 3;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ts_ = getDefaultInstance().getTs();
        onChanged();
        return this;
      }
      /**
       * <code>required string ts = 3;</code>
       */
      public Builder setTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ts_ = value;
        onChanged();
        return this;
      }

      private Object mtype_ = "";
      /**
       * <code>optional string mtype = 4;</code>
       */
      public boolean hasMtype() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string mtype = 4;</code>
       */
      public String getMtype() {
        Object ref = mtype_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mtype_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string mtype = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMtypeBytes() {
        Object ref = mtype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mtype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mtype = 4;</code>
       */
      public Builder setMtype(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mtype = 4;</code>
       */
      public Builder clearMtype() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mtype_ = getDefaultInstance().getMtype();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mtype = 4;</code>
       */
      public Builder setMtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mtype_ = value;
        onChanged();
        return this;
      }

      private Object cfg_ = "";
      /**
       * <code>optional string cfg = 5;</code>
       */
      public boolean hasCfg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string cfg = 5;</code>
       */
      public String getCfg() {
        Object ref = cfg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cfg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string cfg = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCfgBytes() {
        Object ref = cfg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cfg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cfg = 5;</code>
       */
      public Builder setCfg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        cfg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cfg = 5;</code>
       */
      public Builder clearCfg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cfg_ = getDefaultInstance().getCfg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cfg = 5;</code>
       */
      public Builder setCfgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        cfg_ = value;
        onChanged();
        return this;
      }

      private Object code_ = "";
      /**
       * <code>required string code = 6;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string code = 6;</code>
       */
      public String getCode() {
        Object ref = code_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string code = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string code = 6;</code>
       */
      public Builder setCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 6;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 6;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        code_ = value;
        onChanged();
        return this;
      }

      private Object span_ = "";
      /**
       * <code>optional string span = 7;</code>
       */
      public boolean hasSpan() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string span = 7;</code>
       */
      public String getSpan() {
        Object ref = span_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            span_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string span = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSpanBytes() {
        Object ref = span_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          span_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string span = 7;</code>
       */
      public Builder setSpan(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        span_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string span = 7;</code>
       */
      public Builder clearSpan() {
        bitField0_ = (bitField0_ & ~0x00000040);
        span_ = getDefaultInstance().getSpan();
        onChanged();
        return this;
      }
      /**
       * <code>optional string span = 7;</code>
       */
      public Builder setSpanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        span_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.zsy.eg.google.protobuf.bean.TraceApp)
    }

    // @@protoc_insertion_point(class_scope:cn.zsy.eg.google.protobuf.bean.TraceApp)
    private static final UTraceLogBean.TraceApp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UTraceLogBean.TraceApp();
    }

    public static UTraceLogBean.TraceApp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<TraceApp>
        PARSER = new com.google.protobuf.AbstractParser<TraceApp>() {
      public TraceApp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TraceApp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TraceApp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TraceApp> getParserForType() {
      return PARSER;
    }

    public UTraceLogBean.TraceApp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016TraceApp.proto\022\036cn.zsy.eg.google.proto" +
      "buf.bean\"g\n\010TraceApp\022\n\n\002id\030\001 \002(\t\022\013\n\003sys\030" +
      "\002 \002(\t\022\n\n\002ts\030\003 \002(\t\022\r\n\005mtype\030\004 \001(\t\022\013\n\003cfg\030" +
      "\005 \001(\t\022\014\n\004code\030\006 \002(\t\022\014\n\004span\030\007 \001(\tB/\n\036cn." +
      "zsy.eg.google.protobuf.beanB\rUTraceLogBe" +
      "an"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_zsy_eg_google_protobuf_bean_TraceApp_descriptor,
        new String[] { "Id", "Sys", "Ts", "Mtype", "Cfg", "Code", "Span", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
