// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package cn.zsy.eg.google.grpc.helloword;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_zsy_eg_google_grpc_helloword_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_zsy_eg_google_grpc_helloword_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_zsy_eg_google_grpc_helloword_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_zsy_eg_google_grpc_helloword_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\037cn.zsy.eg.google.grp" +
      "c.helloword\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(" +
      "\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2s\n\007Gree" +
      "ter\022h\n\010SayHello\022-.cn.zsy.eg.google.grpc." +
      "helloword.HelloRequest\032+.cn.zsy.eg.googl" +
      "e.grpc.helloword.HelloReply\"\000B:\n\037cn.zsy." +
      "eg.google.grpc.hellowordB\017HelloWorldProt" +
      "oP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_zsy_eg_google_grpc_helloword_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_zsy_eg_google_grpc_helloword_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_zsy_eg_google_grpc_helloword_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_cn_zsy_eg_google_grpc_helloword_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_zsy_eg_google_grpc_helloword_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_zsy_eg_google_grpc_helloword_HelloReply_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
