// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package cn.zsy.eg.google.grpc.helloword;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.zsy.eg.google.grpc.helloword.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
